name: Deploy documentations artefacts [PROD]

on:
    workflow_dispatch:
    workflow_run:
        workflows: [ "Release" ]
        branches: [ master ]
        types:
            - completed

jobs:
    run:
        name: Deploy artifacts [PROD]
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
        uses: ./.github/workflows/documentation-deploy-common.yml
        with:
            path: 'dev'
            ref: 'master'
