name: Release Next Tag

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish feature version
    uses: ./.github/workflows/publish-common.yml
    with:
      with-update-package-lock: true
      auto-options: '--no-changelog'
    secrets:
      gh_token: ${{ secrets.GH_TOKENS_SDDS }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
