name: Typescript coverage

on:
  push:

jobs:
  typescript-coverage:
    runs-on: ubuntu-latest
    env:
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Setup packages
        run: npm i --no-progress --no-audit

      - name: Lerna bootstrap
        run: npx lerna bootstrap

      - name: Run Typescript Coverage
        if: ${{ always() }}
        run: |
          npm run typescript-coverage

      - name: Save artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Typescript Coverage Report Artifacts
          path: /home/runner/work/plasma/plasma/packages/*/coverage-ts/
